### ISSUE TITLE
naming-strategy过时替代？

### ISSUE THREAD

**Issue by zcjlq** [chenfromsz/spring-boot-db#2]
mysql模块 yml配置文件中naming-strategy过时，请问替代方案是什么？谢谢

**Comment by chenfromsz** [comment]
naming-strategy用来配置hiberator的命名规则，没有过时一说。比如命名中有大小的规则，在类中有userId，那么在数据库中就应该表示为：user_id，这也可以用注解@Column(name="user_id")显式的设定。
有关这方面的说明，你可以查看hiberator的说明文档。

**Comment by zcjlq** [comment]
感谢您的解答，hibernate5中naming-strategy不建议使用，请看下面截图，请问如果替换呢
<img width="497" alt="2017-09-04 17 24 25" src="https://user-images.githubusercontent.com/25979570/30020311-f717e334-9195-11e7-98ec-0007b94fb56a.png">
<img width="1092" alt="2017-09-04 17 28 22" src="https://user-images.githubusercontent.com/25979570/30020638-1c92751a-9197-11e7-9de2-e64e26d13a99.png">

**Comment by chenfromsz** [comment]
这里用的是一个配置参数名字：naming-strategy，不是引用这个类org.hibernate.cfg.naming-strategy，而是使用这个参数引用了这个类：org.hibernate.cfg.ImprovedNamingStrategy，这个参数名字naming-strategy不会有过时的说法。

**Comment by chenfromsz** [comment]
补充说明：因为一直在使用，包括更高的版本并未受到影响。如果会有影响的话可以考虑下面替代方法：
naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
